#!/usr/bin/env python3
"""Generate/validate MR. SPICY .strings files from SpicyLocalization.swift.

The Swift fallback catalogue is the single source of truth. This tool:
  * extracts every SpicyStringKey case and every per-language fallback entry
  * verifies English and Arabic cover 100% of the declared keys
  * writes mr-spicy-ui/Localization/{en,ar}.lproj/MrSpicy.strings

Usage:
    python3 tools/sync_strings.py [--check]
"""
from __future__ import annotations

import argparse
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SWIFT = os.path.join(ROOT, "mr-spicy-ui/Sources/SpicyLocalization.swift")
OUT = os.path.join(ROOT, "mr-spicy-ui/Localization")

KEY_RE = re.compile(r'case\s+(\w+)\s*=\s*"([^"]+)"')
ENTRY_RE = re.compile(r'\.(\w+)\s*:\s*"((?:[^"\\]|\\.)*)"\s*,')


def parse() -> tuple[dict[str, str], dict[str, dict[str, str]]]:
    src = open(SWIFT, encoding="utf-8").read()

    enum_block = src.split("public enum SpicyStringKey", 1)[1]
    enum_block = enum_block.split("\npublic final class", 1)[0]
    keys = dict(KEY_RE.findall(enum_block))  # caseName -> key string

    table = src.split("static let fallback", 1)[1]
    langs: dict[str, dict[str, str]] = {}
    for lang in ("english", "arabic"):
        marker = f".{lang}: ["
        if marker not in table:
            continue
        block = table.split(marker, 1)[1]
        depth, end = 1, len(block)
        for i, ch in enumerate(block):
            if ch == "[":
                depth += 1
            elif ch == "]":
                depth -= 1
                if depth == 0:
                    end = i
                    break
        entries = {}
        for case, value in ENTRY_RE.findall(block[:end]):
            if case in keys:
                entries[keys[case]] = value
        langs["en" if lang == "english" else "ar"] = entries
    return keys, langs


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="validate only, do not write")
    args = ap.parse_args()

    keys, langs = parse()
    all_keys = set(keys.values())
    failures = []
    for lang, entries in langs.items():
        missing = sorted(all_keys - set(entries))
        extra = sorted(set(entries) - all_keys)
        print(f"{lang}: {len(entries)}/{len(all_keys)} keys"
              f"{'  MISSING=' + ','.join(missing) if missing else ''}"
              f"{'  EXTRA=' + ','.join(extra) if extra else ''}")
        if missing or extra:
            failures.append(lang)

    if not args.check:
        for lang, entries in langs.items():
            d = os.path.join(OUT, f"{lang}.lproj")
            os.makedirs(d, exist_ok=True)
            with open(os.path.join(d, "MrSpicy.strings"), "w", encoding="utf-8") as fh:
                fh.write("/* MR. SPICY — generated by tools/sync_strings.py. Do not edit by hand. */\n")
                fh.write("/* Source of truth: mr-spicy-ui/Sources/SpicyLocalization.swift */\n\n")
                for key in sorted(entries):
                    fh.write(f'"{key}" = "{entries[key]}";\n')
            print(f"wrote {os.path.relpath(os.path.join(d, 'MrSpicy.strings'), ROOT)}")

    if failures:
        print("LOCALIZATION PARITY: FAIL", file=sys.stderr)
        return 1
    print("LOCALIZATION PARITY: PASS")
    return 0


if __name__ == "__main__":
    sys.exit(main())
